name: sqlproj-staging

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2


    - name: Build SSDT project
      run:  msbuild "GithubAction/DWH_Staging/DWH_Staging.sqlproj" /t:Build /p:Configuration=Release

    - name: Deploy
      uses: azure/sql-action@v2
      with:
        connection-string: ${{ secrets.SQL_CONNECTION_STRING }}
        action: 'publish'
        path: 'GithubAction/DWH_Staging/bin/Debug/DWH_Staging.dacpac'
